### ISSUE TITLE
UI/UX Improvments

### ISSUE THREAD

**Issue by UPstartDeveloper** [UPstartDeveloper/UPstartDeveloper.github.io#3]

**Comment by UPstartDeveloper** [comment]
1. Make icons on index.html the same size
2. Remove the blog, remove the navbar
3. Add a video w/ sound to Roberto, or just use the GIF

**Comment by version0chiro** [comment]
I have mentioned the ways I have worked on these issues in #5 , if there are any other changes please inform me. @UPstartDeveloper

**Comment by UPstartDeveloper** [comment]
Fixed by #4 and #5
